// <auto-generated />
using System;
using AgenciaEventosAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgenciaEventosAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231130044319_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgenciaEventosAPI.Entities.Email", b =>
                {
                    b.Property<int>("EmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("EmailId");

                    b.ToTable("Emails");

                    b.HasData(
                        new
                        {
                            EmailId = 1,
                            Author = "Autor 1",
                            EventId = 1,
                            Message = "Teste de mensagem 1",
                            Receiver = "Recebedor 1",
                            Subject = "Assunto do e-mail 1"
                        },
                        new
                        {
                            EmailId = 2,
                            Author = "Autor 2",
                            EventId = 2,
                            Message = "Teste de mensagem 2",
                            Receiver = "Recebedor 2",
                            Subject = "Assunto do e-mail 2"
                        },
                        new
                        {
                            EmailId = 3,
                            Author = "Autor 3",
                            EventId = 3,
                            Message = "Teste de mensagem 3",
                            Receiver = "Recebedor 3",
                            Subject = "Assunto do e-mail 3"
                        });
                });

            modelBuilder.Entity("AgenciaEventosAPI.Entities.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<int?>("EmailId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("EventId");

                    b.HasIndex("EmailId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            Name = "Evento 1"
                        },
                        new
                        {
                            EventId = 2,
                            Name = "Evento 2"
                        },
                        new
                        {
                            EventId = 3,
                            Name = "Evento 3"
                        });
                });

            modelBuilder.Entity("AgenciaEventosAPI.Entities.Event", b =>
                {
                    b.HasOne("AgenciaEventosAPI.Entities.Email", "Email")
                        .WithMany("Events")
                        .HasForeignKey("EmailId");

                    b.Navigation("Email");
                });

            modelBuilder.Entity("AgenciaEventosAPI.Entities.Email", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
